Add login page
ProjectCopilot/volunteer pull request #39
Opened 2017-07-31 00:53 UTC by gmittal

Closes #28. Looks pretty good. The web copy is still placeholder and needs to be fixed (cc: @ankitr).

@ankitr PTAL.

2017-08-01 05:52 UTC, ankitr requested changes
Great direction. A little feedback and a few questions, but should be good to merge soon.

2017-08-01 05:52 UTC, ankitr commented on app.js
> +app.get('/js/login.js', (req, res) => {
Is this idiomatic? I'm not too familiar with how one configures local javascript.

2017-08-01 05:52 UTC, ankitr commented on static/login.html
> +    <p>Volunteers are the core of our team. This is your chance to help students in need. <ins>This website lets you anonymously support peers who are going through tough times and make sure they get
Can you style this so that the link looks good?

2017-08-01 05:52 UTC, ankitr commented on static/login.html
> +    <div id="login" class="loginBtn google">Login with Google</div>
Make this button span the size of the text, not the width of the container. I think that would look better.

2017-08-01 05:52 UTC, ankitr commented on static/login.html
> +    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
Do we need jQuery for this?

2017-08-01 15:48 UTC, gmittal commented on app.js
> +app.get('/js/login.js', (req, res) => {
Manually replacing config variables as client-side JS is served is a common practice. Though they often use tools like https://github.com/yahoo/express-state to do it. Perhaps I can add this in a future release.

2017-08-01 15:48 UTC, gmittal commented on static/login.html
> +    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
I'm using it for one small thing in ```js/login.js```. I can get rid of it and use vanilla JS too though.

2017-08-01 15:50 UTC, gmittal commented on static/login.html
> +    <p>Volunteers are the core of our team. This is your chance to help students in need. <ins>This website lets you anonymously support peers who are going through tough times and make sure they get
Not sure if I follow. The link is currently just our logo.

2017-08-01 20:14 UTC, gmittal commented on static/login.html
> +    <div id="login" class="loginBtn google">Login with Google</div>
The button is same width as the box of text.

2017-08-01 20:15 UTC, gmittal commented on static/login.html
> +    <div id="login" class="loginBtn google">Login with Google</div>
Also, I'm going to try and get a hold of the official login with Google button.

2017-08-01 21:45 UTC, gmittal commented on static/login.html
> +    <p>Volunteers are the core of our team. This is your chance to help students in need. <ins>This website lets you anonymously support peers who are going through tough times and make sure they get
Oh got it.

2017-08-01 22:15 UTC, gmittal commented on static/login.html
> +    <div id="login" class="loginBtn google">Login with Google</div>
Fixed.

2017-08-01 22:15 UTC, gmittal commented on static/login.html
> +    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
Fixed.

2017-08-01 22:15 UTC, gmittal commented on static/login.html
> +    <p>Volunteers are the core of our team. This is your chance to help students in need. <ins>This website lets you anonymously support peers who are going through tough times and make sure they get
Fixed.

2017-08-02 00:34 UTC, ankitr approved these changes
LGTM

2017-08-02 00:34 UTC, ankitr commented on app.js
> +app.get('/js/login.js', (req, res) => {
Ok, sounds good.

2017-08-02 00:35 UTC, merged